apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: train-test-job
  namespace: argo
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      creationTimestamp: null
    spec:
      restartPolicy: Never
      volumes:
      - name: deploy-yaml-vol
        configMap:
          name: mlserve
          optional: false # must exist
      serviceAccountName: deploy-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl
        command: ['sh', '-c', 'bash /manifests/deploy.sh runs:/10f77abca3994387b52033d324401670/model']
        resources: {}
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow:5000
        volumeMounts:
        - name: deploy-yaml-vol
          mountPath: "/manifests"
          readOnly: true
status: {}

# bash /manifests/deploy.sh runs:/10f77abca3994387b52033d324401670/model