apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: train-test-job
  namespace: argo
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      creationTimestamp: null
    spec:
      restartPolicy: Never
      volumes:
      - name: gapp-creds-vol
        secret:
          secretName: gapp-creds
          optional: false # default setting; "gapps-creds" must exist
      containers:
      - name: train-test-job
        image: argo-step:training
        command: ['sh', '-c', 'sleep 99999']
        resources: {}
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow:5000
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /code/secrets/gapps_creds.json
        volumeMounts:
        - name: gapp-creds-vol
          mountPath: "/code/secrets"
          readOnly: true
          
status: {}