apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  namespace: argo
  name: deploy-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: deploy-sa-role
rules:
- apiGroups: ["apps/v1"] # "" indicates the core API group
  resources: ["deployments.apps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: ClusterRoleBinding
metadata:
  name: deploy-sa-rb
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: deploy-sa
    namespace: argo
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: deploy-sa-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io